sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"
  - "pypy"
  - "pypy3"
script:
  - "pip install -rrequirements.txt -rrequirements_dev.txt"
  - "py.test --showlocals"
  - "flake8 --max-line-length=120 --show-source mozsessiontool.py"
